In [0]:
import pandas as pd
import numpy as np

In [0]:
caesarian = pd.read_csv("caesarian.csv",  names=['Age','Delivery Number','Delivery Time','Blood of Pressure','Heart Problem','Caesarian'])
caesarian.head()

Age  Delivery Number  Delivery Time  Blood of Pressure  Heart Problem  \
0   22                1              0                  2              0   
1   26                2              0                  1              0   
2   26                2              1                  1              0   
3   28                1              0                  2              0   
4   22                2              0                  1              0   

   Caesarian  
0          0  
1          1  
2          0  
3          0  
4          1

In [0]:
# Variabel independen
x = caesarian.drop(["Caesarian"], axis = 1)
x.head()
# Variabel dependen
y = caesarian["Caesarian"]
y.head()    

0    0
1    1
2    0
3    0
4    1
Name: Caesarian, dtype: int64

In [0]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 123)

In [0]:
from sklearn.naive_bayes import GaussianNB
# Mengaktifkan/memanggil/membuat fungsi klasifikasi Naive Bayes
modelnb = GaussianNB()
# Memasukkan data training pada fungsi klasifikasi Naive Bayes
nbtrain = modelnb.fit(x_train, y_train)

In [0]:
# Menentukan hasil prediksi dari x_test
y_pred = nbtrain.predict(x_test)
y_pred

array([1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64)

In [0]:
np.array(y_test)


array([0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0], dtype=int64)

In [0]:
# Menentukan probabilitas hasil prediksi
nbtrain.predict_proba(x_test)

array([[0.13322595, 0.86677405],
       [0.74653837, 0.25346163],
       [0.08698533, 0.91301467],
       [0.70519117, 0.29480883],
       [0.49123283, 0.50876717],
       [0.31283492, 0.68716508],
       [0.01726316, 0.98273684],
       [0.63383692, 0.36616308],
       [0.70894773, 0.29105227],
       [0.80047685, 0.19952315],
       [0.83623454, 0.16376546],
       [0.69456277, 0.30543723],
       [0.75275095, 0.24724905],
       [0.16209657, 0.83790343],
       [0.70894773, 0.29105227],
       [0.77505323, 0.22494677]])

In [0]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[5, 4],
       [5, 2]], dtype=int64)

In [0]:
# Merapikan hasil confusion matrix
y_actual = pd.Series([0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0], name = "actual")
y_pred = pd.Series([1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0], name = "prediction")
df_confusion = pd.crosstab(y_actual, y_pred)

In [0]:
df_confusion

prediction  0  1
actual          
0           5  4
1           5  2

In [0]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.50      0.56      0.53         9
           1       0.33      0.29      0.31         7

    accuracy                           0.44        16
   macro avg       0.42      0.42      0.42        16
weighted avg       0.43      0.44      0.43        16



sumber = https://medium.com/@kurniasp/naive-bayes-classifier-using-scikit-learn-in-python-3067144af115